---
title: "Educational Attainment in our Service Area"
subtitle: "Based on work by Thomas Jay Benjamin for the OAIRP Spring Conference 2023"
author: "Institutional Research"
execute:
    echo: false
params:
    servicearea: "LCCC: Lorain County"
    PUMA1: "00801"
    PUMA2: "00802"
    PUMA3: NULL
    PUMA4: NULL
---

```{R}
#| include: false

# load necessary libraries
library("tidycensus")
library("tidyverse")
library("survey")
library("srvyr")
library("knitr")
```

```{R}
#| include: false
#| cache: true
# pull ACS PUMS data
pums_data <- get_pums(
    year = 2021,
    variables = c("AGEP", "SCHL", "ESR", "SOCP", "HISP", "RAC1P", "CIT"),
    state = "OH",
    puma = c(params$PUMA1, params$PUMA2,
        params$PUMA3, params$PUMA4), # in YAML params$PUMAs = c("00801","00802")
    survey = "acs5",
    recode = TRUE,
    rep_weights = "person"
)

# format ACS PUMS as survey data
pums_survey_data <- pums_data %>%
    to_survey(
        type = "person",
        design = "rep_weights"
    ) %>%
    mutate(
        degree = case_when(
            SCHL >= 22 ~ "Graduate degree",
            SCHL >= 21 ~ "Bachelor's degree",
            SCHL == 20 ~ "Associate's degree",
            SCHL >= 18 ~ "Some college, no degree",
            SCHL >= 16 ~ "High school graduate",
            TRUE ~ "Less than high school"
        ),
        degree = factor(degree, c(
                "Less than high school",
                "High school graduate",
                "Some college, no degree",
                "Associate's degree",
                "Bachelor's degree",
                "Graduate degree"
            )
        ),
        has_degree = SCHL >= 20,
        age_gr = case_when(
            AGEP >= 65 ~ "65+",
            AGEP >= 55 ~ "55-64",
            AGEP >= 45 ~ "45-54",
            AGEP >= 35 ~ "35-44",
            AGEP >= 25 ~ "25-34",
            AGEP >= 18 ~ "18-24",
            TRUE ~ "0-17"
        ),
        race_ethn = case_when(
            CIT == "5" ~ "U.S. \nNonresident",
            HISP != "01" ~ "Hispanic \nor Latino",
            RAC1P == "1" ~ "White",
            RAC1P == "2" ~ "Black or \nAfrican \nAmerican",
            RAC1P == "9" ~ "Two or more \nraces",
            RAC1P == "6" ~ "Asian",
            RAC1P == "8" ~ "Unknown / \nsome other \nrace",
            RAC1P == "3" | RAC1P == "5" ~ "American \nIndian or \nAlaska \nNative",
            RAC1P == "7" ~ "Native \nHawaiian or \nPacific \nIslander",
            TRUE ~ RAC1P
        )
    )
```


After data pre-processing, have data for 7 raw variables we'll be using^[Plus recoded variables and additional identifiers] for the PUMAs associated with the service area for **`r params$servicearea`**.

- AGEP age
- CIT citizenship
- SCHL educational attainment
- ESR employment status
- HISP Hispanic/Latino origin
- RAC1P race
- SOCP occupation

```{R}
pums_survey_data %>%
    group_by(PUMA) %>%
    summarize(
        records = n(),
        weighted = survey_total(vartype = c("ci"), level = 0.95)
    ) %>%
    bind_rows(
        summarize(., across(where(is.numeric), sum),
            across(where(is.character), ~ 'Total')
            )
        ) %>%
    kable(digits = 0, format.args = list(big.mark = ","))
```


## Educational attainment by age

```{R}
 #| include: false
pums_survey_prime_age <- pums_survey_data %>%
    filter(AGEP >= 25 & AGEP < 65) %>%
    group_by(age_gr, degree) %>%
    summarize(
        pct = survey_mean(proportion = TRUE, vartype = c("ci"), level = 0.95),
        n = survey_total(vartype = c("ci"), level = 0.95)
        )
```

Examining educational attainment rates by age group can help identify how the overall educational attainment rate may change over time, and how a higher education institution can have an impact.

```{R}
pums_survey_prime_age %>%
    arrange(age_gr, rev(degree)) %>%
    mutate(label_y = cumsum(n)/sum(n)) %>%
    ggplot(aes(fill = degree, x = age_gr, y = n)) +
        geom_bar(position = "fill", stat = "identity", color = "black") +
        scale_fill_brewer(palette = "Blues") +
        geom_text(aes(y = label_y, label = scales::percent(label_y, accuracy = .1), vjust = 1.5)) +
        scale_y_continuous(name = "population educational attainment rate (cumulative)", labels = scales::percent) +
        labs(x = "age group", fill = "educational attainment") 
```

However, attaiment rates do not tell the complete picture, as the age cohorts may not be all the same size.

```{R}
pums_survey_prime_age %>%
    arrange(age_gr, rev(degree)) %>%
    mutate(label_y = cumsum(n) - .5*n) %>%
    ggplot(aes(fill = degree, x = age_gr, y = n)) +
        geom_bar(position = "stack", stat = "identity", color = "black") +
        scale_fill_brewer(palette = "Blues") +
        geom_text(aes(y = label_y, label = scales::comma(n))) +
        scale_y_continuous(name = "population", labels = scales::comma) +
        labs(x = "age group", fill = "educational attainment")
```

Raising educational attainment may be a necessary strategy to keep good jobs in our area.

```{R}
#| include: false
pums_survey_55to64_emp <- pums_survey_data %>%
    filter(AGEP >= 55 & AGEP < 65 & ESR != 6 & has_degree == TRUE) %>%
    group_by(SOCP, SOCP_label, has_degree) %>%
    summarize(
        n = survey_total(vartype = c("ci"), level = 0.95)
        )
```

### Jobs held by 55-64 year olds with at least an associate's degree:

```{R}
pums_survey_55to64_emp %>%
    select(SOCP_label, SOCP, n, n_low, n_upp) %>%
    arrange(-n) %>%
    head(10) %>%
    kable(
        digits = 0,
        format.args = list(big.mark = ","),
        col.names = c(
            "Occupation",
            "SOC code (ACS)",
            "# Employed",
            "95%CI LB",
            "95%CI UB")
        )
```

## Educational attainment by demographic factors

For this section, we define the educational attainment rate as the proportion of the prime age working population (25-64) with at least an associate's degree.^[This is consistent with Lumina's [Stronger Nation report.](https://www.luminafoundation.org/stronger-nation/report/#/progress)]

### By Public Use Microdata Area (PUMA)

```{R}
 #| include: false
pums_survey_PUMAs <- pums_survey_data %>%
    filter(AGEP >= 25 & AGEP < 65) %>%
    group_by(PUMA, has_degree) %>%
    summarize(
        pct = survey_mean(proportion = TRUE, vartype = c("ci"), level = 0.95),
        n = survey_total(vartype = c("ci"), level = 0.95)
        )
```

```{R}
pums_survey_PUMAs %>%
    filter(has_degree == TRUE) %>%
    ggplot(aes(fill = has_degree, x = PUMA, y = pct)) +
        geom_bar(position = "stack", stat = "identity", color = "black") +
        geom_errorbar(aes(ymin = pct_low, ymax = pct_upp, width = 0.2)) +
        scale_fill_brewer(palette = "Blues", guide = "none") +
        geom_text(aes(y = pct/2, label = scales::percent(pct, accuracy = .1))) +
        scale_y_continuous(name = "educational attainment rate", labels = scales::percent) +
        labs(x = "PUMA")
```

### By Race & Ethnicity

```{R}
 #| include: false
pums_survey_RE <- pums_survey_data %>%
    filter(AGEP >= 25 & AGEP < 65) %>%
    group_by(race_ethn, has_degree) %>%
    summarize(
        pct = survey_mean(proportion = TRUE, vartype = c("ci"), level = 0.95),
        n = survey_total(vartype = c("ci"), level = 0.95)
        )
```

```{R}
pums_survey_RE %>%
    filter(has_degree == TRUE) %>%
    ggplot(aes(fill = has_degree, x = race_ethn, y = pct)) +
        geom_bar(position = "stack", stat = "identity", color = "black") +
        geom_errorbar(aes(ymin = pct_low, ymax = pct_upp, width = 0.2)) +
        scale_fill_brewer(palette = "Blues", guide = "none") +
        geom_text(aes(y = pct/2, label = scales::percent(pct, accuracy = .1))) +
        scale_y_continuous(name = "educational attainment rate", labels = scales::percent) +
        labs(x = "Race/Ethnicity")
```

## Top occupations in our service area by educational attainment

```{R}
#| include: false
pums_survey_by_occ <- pums_survey_data %>%
    filter(AGEP >= 25 & AGEP < 65 & ESR != 6) %>%
    group_by(SOCP, SOCP_label, degree) %>%
    summarize(
        n = survey_total(vartype = c("ci"), level = 0.95)
        )
```

### Individuals with an Associate's degree

```{R}
pums_survey_by_occ %>%
    filter(degree == "Associate's degree") %>%
    select(SOCP_label, SOCP, n, n_low, n_upp) %>%
    arrange(-n) %>%
    head(10) %>%
    kable(
        digits = 0,
        format.args = list(big.mark = ","),
        col.names = c(
            "Occupation",
            "SOC code (ACS)",
            "# Employed",
            "95%CI LB",
            "95%CI UB")
        )
```

### Individuals with an Bachelor's degree

```{R}
pums_survey_by_occ %>%
    filter(degree == "Bachelor's degree") %>%
    select(SOCP_label, SOCP, n, n_low, n_upp) %>%
    arrange(-n) %>%
    head(10) %>%
    kable(
        digits = 0,
        format.args = list(big.mark = ","),
        col.names = c(
            "Occupation",
            "SOC code (ACS)",
            "# Employed",
            "95%CI LB",
            "95%CI UB")
        )
```

### Individuals with a graduate degree

```{R}
pums_survey_by_occ %>%
    filter(degree == "Graduate degree") %>%
    select(SOCP_label, SOCP, n, n_low, n_upp) %>%
    arrange(-n) %>%
    head(10) %>%
    kable(
        digits = 0,
        format.args = list(big.mark = ","),
        col.names = c(
            "Occupation",
            "SOC code (ACS)",
            "# Employed",
            "95%CI LB",
            "95%CI UB")
        )
```

### Individuals with some college, no degree

```{R}
pums_survey_by_occ %>%
    filter(degree == "Some college, no degree") %>%
    select(SOCP_label, SOCP, n, n_low, n_upp) %>%
    arrange(-n) %>%
    head(10) %>%
    kable(
        digits = 0,
        format.args = list(big.mark = ","),
        col.names = c(
            "Occupation",
            "SOC code (ACS)",
            "# Employed",
            "95%CI LB",
            "95%CI UB")
        )
```

### Individuals with only a high school education

```{R}
pums_survey_by_occ %>%
    filter(degree == "High school graduate") %>%
    select(SOCP_label, SOCP, n, n_low, n_upp) %>%
    arrange(-n) %>%
    head(10) %>%
    kable(
        digits = 0,
        format.args = list(big.mark = ","),
        col.names = c(
            "Occupation",
            "SOC code (ACS)",
            "# Employed",
            "95%CI LB",
            "95%CI UB")
        )
```

### Individuals with less than a high school education

```{R}
pums_survey_by_occ %>%
    filter(degree == "Less than high school") %>%
    select(SOCP_label, SOCP, n, n_low, n_upp) %>%
    arrange(-n) %>%
    head(10) %>%
    kable(
        digits = 0,
        format.args = list(big.mark = ","),
        col.names = c(
            "Occupation",
            "SOC code (ACS)",
            "# Employed",
            "95%CI LB",
            "95%CI UB")
        )
```